/**
 * Demo data — powers all dashboard pages when DEMO_MODE=true or no database configured.
 * This lets the app run immediately after `npm install && npm run dev` with zero config.
 */

export const DEMO_USER = {
  id: "demo-user-1",
  name: "Sarah Chen",
  email: "sarah@demo.com",
  image: null,
  role: "ADMIN" as const,
  tenantId: "demo-tenant-1",
};

export const DEMO_TENANT = {
  id: "demo-tenant-1",
  name: "Acme Corp",
  slug: "acme-corp",
  plan: "PRO" as const,
  stripeCustomerId: null,
  stripeSubscriptionId: null,
  onboardingCompleted: true,
  config: {
    businessName: "Acme Corp",
    businessPhone: "+34911234567",
    assistantLanguage: "es",
    assistantTone: "profesional",
    greetingMessage: "Hola, gracias por llamar a Acme Corp. ¿En qué puedo ayudarle?",
    propertyTypes: ["PISO", "CASA", "LOCAL", "OFICINA", "TERRENO"],
  },
};

export const DEMO_STATS = {
  totalProjects: 12,
  activeProjects: 8,
  totalUsers: 5,
  totalRevenue: 24500,
  revenueChange: 12.5,
  usersChange: 8.2,
  projectsChange: 15.0,
};

export const DEMO_PROJECTS = [
  { id: "p1", name: "Website Redesign", description: "Complete redesign of the marketing site with new brand", status: "ACTIVE", priority: "HIGH", createdAt: "2026-03-15T10:00:00Z", updatedAt: "2026-04-01T14:30:00Z", owner: { name: "Sarah Chen" }, _count: { tasks: 24 } },
  { id: "p2", name: "Mobile App v2", description: "React Native app with push notifications and offline mode", status: "ACTIVE", priority: "HIGH", createdAt: "2026-02-20T08:00:00Z", updatedAt: "2026-04-02T09:15:00Z", owner: { name: "James Wilson" }, _count: { tasks: 38 } },
  { id: "p3", name: "API Gateway", description: "Centralized API gateway with rate limiting and auth", status: "ACTIVE", priority: "MEDIUM", createdAt: "2026-03-01T12:00:00Z", updatedAt: "2026-03-28T16:45:00Z", owner: { name: "Sarah Chen" }, _count: { tasks: 15 } },
  { id: "p4", name: "Analytics Dashboard", description: "Real-time analytics with custom reports and exports", status: "ACTIVE", priority: "MEDIUM", createdAt: "2026-03-10T09:00:00Z", updatedAt: "2026-04-01T11:00:00Z", owner: { name: "Emily Park" }, _count: { tasks: 19 } },
  { id: "p5", name: "Payment Integration", description: "Stripe integration with subscription management", status: "COMPLETED", priority: "HIGH", createdAt: "2026-01-15T10:00:00Z", updatedAt: "2026-03-20T15:00:00Z", owner: { name: "James Wilson" }, _count: { tasks: 12 } },
  { id: "p6", name: "CI/CD Pipeline", description: "Automated testing and deployment with GitHub Actions", status: "ACTIVE", priority: "LOW", createdAt: "2026-03-25T14:00:00Z", updatedAt: "2026-04-02T10:00:00Z", owner: { name: "Alex Kim" }, _count: { tasks: 8 } },
];

export const DEMO_TEAM = [
  { id: "u1", name: "Sarah Chen", email: "sarah@demo.com", role: "ADMIN", image: null, createdAt: "2025-06-01T00:00:00Z" },
  { id: "u2", name: "James Wilson", email: "james@demo.com", role: "MEMBER", image: null, createdAt: "2025-07-15T00:00:00Z" },
  { id: "u3", name: "Emily Park", email: "emily@demo.com", role: "MEMBER", image: null, createdAt: "2025-09-01T00:00:00Z" },
  { id: "u4", name: "Alex Kim", email: "alex@demo.com", role: "MEMBER", image: null, createdAt: "2026-01-10T00:00:00Z" },
  { id: "u5", name: "Maria Santos", email: "maria@demo.com", role: "VIEWER", image: null, createdAt: "2026-02-20T00:00:00Z" },
];

export const DEMO_REVENUE_DATA = [
  { month: "Oct", revenue: 12400, users: 120 },
  { month: "Nov", revenue: 15800, users: 145 },
  { month: "Dec", revenue: 14200, users: 138 },
  { month: "Jan", revenue: 18600, users: 167 },
  { month: "Feb", revenue: 21300, users: 189 },
  { month: "Mar", revenue: 24500, users: 215 },
];

export const DEMO_ACTIVITY = [
  { id: "a1", user: "Sarah Chen", action: "created project", target: "Website Redesign", time: "2 hours ago" },
  { id: "a2", user: "James Wilson", action: "completed task", target: "Setup CI pipeline", time: "4 hours ago" },
  { id: "a3", user: "Emily Park", action: "commented on", target: "Analytics Dashboard", time: "5 hours ago" },
  { id: "a4", user: "Alex Kim", action: "pushed to", target: "API Gateway", time: "6 hours ago" },
  { id: "a5", user: "Maria Santos", action: "reviewed", target: "Mobile App v2 PR #42", time: "8 hours ago" },
];

export const DEMO_INVOICES = [
  { id: "inv1", date: "2026-04-01", amount: 29, status: "paid", plan: "Pro" },
  { id: "inv2", date: "2026-03-01", amount: 29, status: "paid", plan: "Pro" },
  { id: "inv3", date: "2026-02-01", amount: 29, status: "paid", plan: "Pro" },
  { id: "inv4", date: "2026-01-01", amount: 0, status: "paid", plan: "Free (Trial)" },
];

/** Check if we're in demo mode */
export function isDemoMode(): boolean {
  return process.env.DEMO_MODE === "true" || !process.env.DATABASE_URL;
}

// ─── Real Estate Metrics ────────────────────────────────

export const DEMO_METRICS = {
  totalProperties: 24,
  activeProperties: 18,
  totalLeads: 78,
  newLeadsThisMonth: 12,
  totalCalls: 210,
  callsThisMonth: 43,
  conversionRate: 23.5,
  avgPrice: 289000,
};

export const DEMO_MONTHLY_DATA = [
  { month: "Nov", properties: 2, leads: 8, calls: 22 },
  { month: "Dic", properties: 3, leads: 11, calls: 28 },
  { month: "Ene", properties: 5, leads: 14, calls: 35 },
  { month: "Feb", properties: 4, leads: 16, calls: 40 },
  { month: "Mar", properties: 6, leads: 18, calls: 48 },
  { month: "Abr", properties: 4, leads: 12, calls: 37 },
];

export const DEMO_PROPERTIES = [
  {
    id: "prop-1",
    title: "Luminoso ático con vistas al mar",
    city: "Barcelona",
    description: "Espectacular ático reformado con vistas panorámicas. Dispone de terraza de 30m², cocina equipada y acabados de lujo.",
    operationType: "VENTA",
    propertyType: "PISO",
    price: 350000,
    currency: "EUR",
    status: "DISPONIBLE",
    usableSurface: 85,
    builtSurface: 95,
    bedrooms: 3,
    bathrooms: 2,
    toilets: 1,
    floor: "8ª",
    hasElevator: true,
    terrace: true,
    balcony: false,
    garage: true,
    storageRoom: false,
    pool: false,
    airConditioning: true,
    heating: true,
    energyCert: "B",
    address: "Calle del Mar 42, 08001 Barcelona",
    latitude: 41.3874,
    longitude: 2.1686,
    zone: "Centro",
    hideExactAddress: false,
    photos: [],
    user: { name: "Sarah Chen" },
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-04-01T14:30:00Z",
  },
  {
    id: "prop-2",
    title: "Casa adosada con piscina en urbanización",
    city: "Madrid",
    description: "Preciosa casa adosada en urbanización privada con piscina comunitaria. 4 habitaciones, jardín privado y garaje.",
    operationType: "VENTA",
    propertyType: "CASA",
    price: 525000,
    currency: "EUR",
    status: "DISPONIBLE",
    usableSurface: 130,
    builtSurface: 150,
    bedrooms: 4,
    bathrooms: 3,
    toilets: 1,
    floor: null,
    hasElevator: false,
    terrace: true,
    balcony: false,
    garage: true,
    storageRoom: true,
    pool: true,
    airConditioning: true,
    heating: true,
    energyCert: "C",
    address: "Av. de la Sierra 15, 28001 Madrid",
    latitude: 40.4168,
    longitude: -3.7038,
    zone: "Norte",
    hideExactAddress: false,
    photos: [],
    user: { name: "James Wilson" },
    createdAt: "2026-02-20T08:00:00Z",
    updatedAt: "2026-04-02T09:15:00Z",
  },
  {
    id: "prop-3",
    title: "Local comercial en zona céntrica",
    city: "Valencia",
    description: "Local comercial en plena calle mayor. Ideal para negocio con gran afluencia de público. 50m² diáfanos.",
    operationType: "ALQUILER",
    propertyType: "LOCAL",
    price: 1500,
    currency: "EUR",
    status: "DISPONIBLE",
    usableSurface: 45,
    builtSurface: 50,
    bedrooms: 0,
    bathrooms: 1,
    toilets: 0,
    floor: "baja",
    hasElevator: false,
    terrace: false,
    balcony: false,
    garage: false,
    storageRoom: false,
    pool: false,
    airConditioning: true,
    heating: false,
    energyCert: "D",
    address: "Calle Mayor 7, 46001 Valencia",
    latitude: 39.4699,
    longitude: -0.3763,
    zone: "Centro",
    hideExactAddress: false,
    photos: [],
    user: { name: "Emily Park" },
    createdAt: "2026-03-01T12:00:00Z",
    updatedAt: "2026-03-28T16:45:00Z",
  },
  {
    id: "prop-4",
    title: "Oficina diáfana con parking incluido",
    city: "Madrid",
    description: "Oficina en edificio corporativo con 24h de seguridad. Parking incluido en el precio. Ideal para empresa tecnológica.",
    operationType: "ALQUILER",
    propertyType: "OFICINA",
    price: 2500,
    currency: "EUR",
    status: "RESERVADO",
    usableSurface: 90,
    builtSurface: 100,
    bedrooms: 0,
    bathrooms: 2,
    toilets: 1,
    floor: "3ª",
    hasElevator: true,
    terrace: false,
    balcony: false,
    garage: true,
    storageRoom: false,
    pool: false,
    airConditioning: true,
    heating: true,
    energyCert: "A",
    address: "Calle Tecnología 45, 28050 Madrid",
    latitude: 40.4381,
    longitude: -3.6910,
    zone: "Tecnología",
    hideExactAddress: false,
    photos: [],
    user: { name: "Sarah Chen" },
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-04-01T11:00:00Z",
  },
  {
    id: "prop-5",
    title: "Terreno urbanizable con vistas",
    city: "Málaga",
    description: "Parcela de 500m² urbanizable con vistas despejadas. Ideal para construir vivienda unifamiliar. Todos los servicios disponibles.",
    operationType: "VENTA",
    propertyType: "TERRENO",
    price: 180000,
    currency: "EUR",
    status: "DISPONIBLE",
    usableSurface: 500,
    builtSurface: null,
    bedrooms: 0,
    bathrooms: 0,
    toilets: 0,
    floor: null,
    hasElevator: false,
    terrace: false,
    balcony: false,
    garage: false,
    storageRoom: false,
    pool: false,
    airConditioning: false,
    heating: false,
    energyCert: null,
    address: "Paraje Los Olivos, 29700 Málaga",
    latitude: 36.7213,
    longitude: -4.4214,
    zone: "Costa",
    hideExactAddress: true,
    photos: [],
    user: { name: "Alex Kim" },
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-03-20T15:00:00Z",
  },
  {
    id: "prop-6",
    title: "Piso céntrico reformado para alquiler vacacional",
    city: "Valencia",
    description: "Piso completamente reformado en el casco histórico. Ideal para alquiler vacacional. 2 habitaciones, aire acondicionado, cocina americana.",
    operationType: "ALQUILER_VACACIONAL",
    propertyType: "PISO",
    price: 1200,
    currency: "EUR",
    status: "DISPONIBLE",
    usableSurface: 60,
    builtSurface: 70,
    bedrooms: 2,
    bathrooms: 1,
    toilets: 0,
    floor: "2ª",
    hasElevator: false,
    terrace: true,
    balcony: false,
    garage: false,
    storageRoom: false,
    pool: false,
    airConditioning: true,
    heating: true,
    energyCert: "C",
    address: "Plaza del Ayuntamiento 3, 46002 Valencia",
    latitude: 39.4702,
    longitude: -0.3768,
    zone: "Casco Histórico",
    hideExactAddress: false,
    photos: [],
    user: { name: "Emily Park" },
    createdAt: "2026-03-25T14:00:00Z",
    updatedAt: "2026-04-02T10:00:00Z",
  },
];

export const DEMO_LEADS = [
  {
    id: "lead-1",
    nombre: "Carlos Martínez",
    telefono: "+34 612 345 678",
    email: "carlos@email.com",
    presupuesto: 350000,
    canal: "llamada_telefonica",
    financiacion: true,
    urgencia: "inmediata",
    idioma: "es",
    propertyId: "prop-1",
    property: { id: "prop-1", title: "Luminoso ático con vistas al mar" },
    tipoConsulta: "comprar",
    estado: "Nuevo",
    notasAgente: "Cliente interesado en ático. Busca mudanza urgente.",
    notas: "Llamó preguntando por el ático del centro. Tiene pareja y dos hijos.",
    ultimoContacto: "2026-04-10T10:30:00Z",
    createdAt: "2026-04-10T10:30:00Z",
    user: { name: "Sarah Chen" },
  },
  {
    id: "lead-2",
    nombre: "Ana García",
    telefono: "+34 655 123 456",
    email: "ana@email.com",
    presupuesto: 1500,
    canal: "web",
    financiacion: false,
    urgencia: "primer_mes",
    idioma: "es",
    propertyId: "prop-3",
    property: { id: "prop-3", title: "Local comercial en zona céntrica" },
    tipoConsulta: "alquilar",
    estado: "Contactado",
    notasAgente: "Ya contactamos, va a visitar el local mañana.",
    notas: "Rellenó formulario web interesada en local para tienda de ropa.",
    ultimoContacto: "2026-04-09T16:00:00Z",
    createdAt: "2026-04-08T09:15:00Z",
    user: { name: "Emily Park" },
  },
  {
    id: "lead-3",
    nombre: "Miguel Torres",
    telefono: "+34 688 777 888",
    email: "miguel@email.com",
    presupuesto: 180000,
    canal: "whatsapp",
    financiacion: true,
    urgencia: "sin_urgencia",
    idioma: "es",
    propertyId: "prop-5",
    property: { id: "prop-5", title: "Terreno urbanizable con vistas" },
    tipoConsulta: "comprar",
    estado: "Visita_programada",
    notasAgente: "Visita programada para el sábado a las 11:00.",
    notas: "Contactó por WhatsApp. Quiere terreno para construir casa.",
    ultimoContacto: "2026-04-09T12:00:00Z",
    createdAt: "2026-04-07T14:00:00Z",
    user: { name: "Alex Kim" },
  },
  {
    id: "lead-4",
    nombre: "Laura Sánchez",
    telefono: "+34 699 111 222",
    email: "laura@email.com",
    presupuesto: 525000,
    canal: "llamada_telefonica",
    financiacion: true,
    urgencia: "primer_mes",
    idioma: "es",
    propertyId: "prop-2",
    property: { id: "prop-2", title: "Casa adosada con piscina en urbanización" },
    tipoConsulta: "comprar",
    estado: "Ganado",
    notasAgente: "¡Cerrado! Firma la semana que viene.",
    notas: "Familia con hijos. Les encantó la casa con piscina. Aceptaron condiciones.",
    ultimoContacto: "2026-04-05T09:00:00Z",
    createdAt: "2026-03-20T11:00:00Z",
    user: { name: "James Wilson" },
  },
  {
    id: "lead-5",
    nombre: "Roberto Díaz",
    telefono: "+34 644 555 666",
    email: null,
    presupuesto: null,
    canal: "llamada_telefonica",
    financiacion: false,
    urgencia: "sin_urgencia",
    idioma: "en",
    propertyId: null,
    tipoConsulta: "tasar",
    estado: "Descartado",
    notasAgente: "No le interesaron nuestros servicios. Descartado.",
    notas: "Llamó para tasar su piso pero no quiere vender por ahora.",
    ultimoContacto: "2026-04-01T15:00:00Z",
    createdAt: "2026-03-28T10:00:00Z",
    user: { name: "Sarah Chen" },
  },
];

export const DEMO_CALLS = [
  {
    id: "call-1",
    vapiCallId: "vapi-call-001",
    leadId: "lead-1",
    customerPhone: "+34 612 345 678",
    duracion: 245,
    grabacionUrl: null,
    transcripcion: "Carlos: Hola, llamaba por el ático que tienen anunciado...\nAgente: ¡Buenos días! Sí, el ático del centro con vistas al mar.\nCarlos: ¿Sigue disponible?\nAgente: Sí, está disponible. Tiene 85m² útiles, 3 habitaciones...",
    resumen: "Cliente interesado en ático. Busca mudanza urgente. Tiene presupuesto de 350.000€. Necesita financiación.",
    satisfaccion: "bien",
    coste: 0.045,
    estado: "completada",
    startedAt: "2026-04-10T10:30:00Z",
    endedAt: "2026-04-10T10:34:05Z",
    createdAt: "2026-04-10T10:34:05Z",
  },
  {
    id: "call-2",
    vapiCallId: "vapi-call-002",
    leadId: "lead-4",
    customerPhone: "+34 699 111 222",
    duracion: 480,
    grabacionUrl: null,
    transcripcion: "Laura: Quería más información sobre la casa con piscina...\nAgente: ¡Por supuesto! Es una casa adosada de 150m²...",
    resumen: "Familia interesada en la casa adosada. Quieren visitarla en fin de semana. Presupuesto ajustado.",
    satisfaccion: "bien",
    coste: 0.089,
    estado: "completada",
    startedAt: "2026-03-20T11:00:00Z",
    endedAt: "2026-03-20T11:08:00Z",
    createdAt: "2026-03-20T11:08:00Z",
  },
  {
    id: "call-3",
    vapiCallId: "vapi-call-003",
    leadId: "lead-5",
    customerPhone: "+34 644 555 666",
    duracion: 120,
    grabacionUrl: null,
    transcripcion: "Roberto: Hello, I was calling about a property valuation...\nAgente: Hello! How can I help you?",
    resumen: "Cliente llamó para tasar propiedad. No interesado en compra/venta. Inglés.",
    satisfaccion: "indiferente",
    coste: 0.023,
    estado: "completada",
    startedAt: "2026-03-28T10:00:00Z",
    endedAt: "2026-03-28T10:02:00Z",
    createdAt: "2026-03-28T10:02:00Z",
  },
  {
    id: "call-4",
    vapiCallId: "vapi-call-004",
    leadId: null,
    customerPhone: "+34 677 333 444",
    duracion: 30,
    grabacionUrl: null,
    transcripcion: null,
    resumen: "Llamada perdida. No dejó mensaje.",
    satisfaccion: null,
    coste: null,
    estado: "no_contesta",
    startedAt: "2026-04-11T08:15:00Z",
    endedAt: "2026-04-11T08:15:30Z",
    createdAt: "2026-04-11T08:15:30Z",
  },
];
